data_load:
  train_csv: 'data/raw/train.csv'
  test_csv: 'data/raw/test.csv'

preprocess_category:
  TARGET_COL: [ 'SalePrice' ]
  ID_COL: 'Id'
  CAT_COLS: [ 'MSZoning', 'Street', 'Alley', 'LotShape', 'LandContour', 'Utilities', 'LotConfig', 'LandSlope', 'Neighborhood', 'Condition1', 'Condition2', 'BldgType', 'HouseStyle', 'RoofStyle', 'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrType', 'ExterQual', 'ExterCond', 'Foundation', 'BsmtQual', 'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinType2', 'Heating', 'HeatingQC', 'CentralAir', 'Electrical', 'KitchenQual', 'Functional', 'FireplaceQu', 'GarageType', 'GarageFinish', 'GarageQual', 'GarageCond', 'PavedDrive', 'PoolQC', 'Fence', 'MiscFeature', 'SaleType', 'SaleCondition' ]
  REAL_COLS: [ 'MSSubClass', 'OverallQual', 'OverallCond', 'LotFrontage', 'LotArea', 'MasVnrArea', 'BsmtFinSF1', 'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', '1stFlrSF', '2ndFlrSF', 'LowQualFinSF', 'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath', 'HalfBath', 'BedroomAbvGr', 'KitchenAbvGr', 'TotRmsAbvGrd','Fireplaces', 'GarageCars', 'GarageArea', 'WoodDeckSF', 'OpenPorchSF', 'EnclosedPorch', '3SsnPorch', 'ScreenPorch', 'PoolArea', 'MiscVal' ]
  DATA_COLS: [ 'YearBuilt', 'YearRemodAdd', 'GarageYrBlt', 'MoSold', 'YrSold' ]

  BASEMENT_COLS: [ 'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinType2' ]
  MASONRY_COLS: [ 'MasVnrArea' ]
  GARAGE_COLS: [ 'GarageFinish', 'GarageQual', 'GarageCond' ]
  GARAGE_COL: [ 'GarageYrBlt' ]

  MAX_NUMBER_NAN_VALUE_COLS: [ 'PoolQC', 'Fence', 'MiscFeature', 'Alley', 'BsmtQual', 'GarageType' , 'FireplaceQu' ]
  NUMBER_OF_TEST: 15

interim_paths:
  data_for_train_pkl: 'data/interim/data_for_train.pkl'
  val_pkl: 'data/interim/val.pkl'

processed_paths:
  target_data_train_pkl: 'data/processed/target_for_data_for_train.pkl'
  processed_test_pkl: 'data/processed/test.pkl'
  processed_data_for_train_pkl: 'data/processed/data_for_train.pkl'

train:
  COL: ['Пол', 'Семья', 'Этнос', 'Национальность', 'Религия', 'Профессия', 'Вы работаете?', 'Выход на пенсию', 'Прекращение работы по болезни', 'Сахарный диабет', 'Гепатит', 'Онкология', 'Хроническое заболевание легких', 'Бронжиальная астма', 'Туберкулез легких ', 'ВИЧ/СПИД', 'Регулярный прим лекарственных средств', 'Травмы за год', 'Переломы', 'Статус Курения', 'Пассивное курение', 'Частота пасс кур', 'Алкоголь', 'Сова/Жаворонок/Голубь', 'Часов сна', 'Сон после обеда', 'Спорт, клубы', 'Религия, клубы', 'Образование_ord', 'Возраст курения', 'Сигарет в день', 'Возраст алког']
  CATEGORIES_COL_AFTER_PREP: ['Пол','Семья', 'Этнос', 'Национальность', 'Религия', 'Профессия', 'Статус Курения', 'Частота пасс кур', 'Алкоголь', 'Сова/Жаворонок/Голубь']
  test_size: 0.2
  iterations: 10
  loss_function: 'MultiLogloss'
  eval_metric: 'MultiLogloss'
  learning_rate: 0.01
  bootstrap_type: 'Bayesian'
  boost_from_average: False
  ctr_leaf_count_limit: 3
  leaf_estimation_iterations: 1
  leaf_estimation_method: 'Gradient'

  model_catboost_path: 'models/model_catboost.joblib'
  model_lgbm_path: 'models/model_lgbm.joblib'
  X_test_path: 'data/processed/X_test_data.pkl'
  Y_test_path: 'data/processed/Y_test_data.pkl'

evaluate:
  score_metric: 'f1'
  score_path_catboost: 'reports/metrics_catboost.json'
  score_path_lightgbm: 'reports/metrics_lightgbm.json'
  score_path_rocauc_samples_catboost: 'reports/metrics_rocauc_catboost.csv'
  score_path_rocauc_samples_lgbm: 'reports/metrics_rocauc_lgbm.csv'
